# Generated by Django 3.1.7 on 2021-03-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=120, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('pubyear', models.IntegerField(null=True)),
                ('abstract', models.TextField(max_length=400, null=True)),
                ('author', models.ManyToManyField(null=True, to='books.Author')),
            ],
        ),
    ]
